### ISSUE TITLE
Ability to map mouse clicks/movement to modifier + stick etc

### ISSUE THREAD

**Issue by dannyglover** [cyber-sushi/makima#10]
Hello again.

When I used to use Windows, I used controller companion to do the following:

- Whilst select held > right analog stick moves the mouse.
- Whilst select held + RB pressed > mouse right click.
- Whilst select held + LB pressed > mouse left click.

This solves the problem with just mapping the right stick to the mouse, which will cause it to move the mouse all the time. I don't know if you support mouse events bound to remaps, but it would be a great feature to include, and for me personally, it would complete my missing bindings since switching back to Linux.

Thanks again.

**Comment by cyber-sushi** [comment]
You can bind your mouse buttons with
```
BTN_SELECT-BTN_TR = ["BTN_RIGHT"]
BTN_SELECT-BTN_TL = ["BTN_LEFT"]
```

By "move the mouse all the time" you mean that even when idle, your sticks moves the mouse? In that case, you could increase the deadzone through the `RSTICK_DEADZONE` parameter. Or do you just want to completely disable the stick, and only enable it when select is pressed? I can implement that if needed

Also, is everything okay regarding issue #9? So I can close that if it's fixed

**Comment by dannyglover** [comment]
> You can bind your mouse buttons with
> 
> ```
> BTN_SELECT-BTN_TR = ["BTN_RIGHT"]
> BTN_SELECT-BTN_TL = ["BTN_LEFT"]
> ```
> 
> By "move the mouse all the time" you mean that even when idle, your sticks moves the mouse? In that case, you could increase the deadzone through the `RSTICK_DEADZONE` parameter. Or do you just want to completely disable the stick, and only enable it when select is pressed? I can implement that if needed
> 
> Also, is everything okay regarding issue #9? So I can close that if it's fixed

By "move the mouse all the time" I mean that whenever the stick is moved by your thumb, which naturally isn't great when playing a game with controller support. By forcing it only to be active whilst a modifier is held, it makes it so you only get the mouse move functionality when you specifically need it.

I'm not suggesting to remove the option you have currently, but being able to make it so it only activates when a modifier is held would be excellent, as it's unusable for my use case as things stand.

Regarding #9 I didn't realise a fix was pushed. I'll check that out shortly and report back on that issues thread. 

Thanks again!

**Comment by cyber-sushi** [comment]
Just pushed version 0.7.2 which includes enabling analog sticks when pressing specific keys/buttons/modifiers (if no modifiers are set, they act as before), let me know if this works for you

The syntax for your use case would be
```
RSTICK = "cursor"
RSTICK_ACTIVATION_MODIFIERS = "BTN_SELECT"
```

**Comment by dannyglover** [comment]
> Just pushed version 0.7.2 which includes enabling analog sticks when pressing specific keys/buttons/modifiers (if no modifiers are set, they act as before), let me know if this works for you
> 
> The syntax for your use case would be
> 
> ```
> RSTICK = "cursor"
> RSTICK_ACTIVATION_MODIFIERS = "BTN_SELECT"
> ```

That works great. Thank you very much!
