### ISSUE TITLE
v0.8.0 broke smooth scroll

### ISSUE THREAD

**Issue by pintassilgo** [cyber-sushi/makima#11]
Hi, I'm "*the reddit dude*" who reported a few bugs and made suggestions past month.

I just tried v0.8.0 and had to downgrade because it changed my scroll wheel for worse, notably on Firefox.

**Comment by cyber-sushi** [comment]
Hello!

I can confirm the behavior, I'm looking into it

**Comment by cyber-sushi** [comment]
Should be fixed with version 0.8.1!
Version 0.8.0 was a major rewrite so I expected to have missed something, thank you for the report

Let me know if it works properly now
