### ISSUE TITLE
App-specific binding isn't working on KDE Plasma

### ISSUE THREAD

**Issue by pintassilgo** [cyber-sushi/makima#13]
I'm probably doing something wrong, maybe you can please help me.

So to test this new feature of v0.9.0 I first downloaded [kdotool tarball](https://github.com/jinliu/kdotool/releases/latest) then extracted the binary to `~/.local/bin`.

I confirmed `print $XDG_CURRENT_DESKTOP` returns `KDE`.

To run a simple test, I duplicated my keyboard toml file appending window class. I don't know if there's a easier way to get window class, so I used "Detect Window Properties" from Window Rules  (Kwin). The app I chose to test was Kate, which is Plasma default editor. I'm not sure if its window class is `kate` or `org.kde.kate`, but I tried both separately and none worked. So, for me, filename was `Usb KeyBoard Usb KeyBoard::kate.toml` or `Usb KeyBoard Usb KeyBoard::org.kde.kate.toml`.

Content was simple this:
    
    [remap]
    KEY_A = ["KEY_B"]

So that pressing `A` key should print `b`.

Restarted systemd service but... it doesn't work.

Maybe kdotool needs to be available as root, so I placed the file in `/usr/bin` and restarted the service, but it still doesn't work.

Am I missing something?

Thanks.

**Comment by cyber-sushi** [comment]
Hello, thanks for your report!

I've only tested it on a Debian KDE live USB with the following conditions and it works:

- Kdotool executable inside `/usr/bin/`, but it shouldn't make any difference as long as the directory is in PATH
- Makima launched as root with `sudo -E makima`
- App-specific bindings for Konsole, with `::konsole.toml` at the end of the config file

There are two things that I can think of:

- Does `kdotool getactivewindow getwindowclassname` work in your terminal? It should just print `konsole`
- Are you running Makima as a systemd service? I haven't tested that scenario, but that may be the culprit so I'll check it tomorrow. Also, just to make sure, can you post your systemd unit?

**Comment by cyber-sushi** [comment]
Hello, I've done a couple of changes in v0.9.1 to correctly intercept stdout from kdotool and redirect stderr to null when running as a systemd service

I can't test if this works because in my Debian live ISO I don't seem to be able to access uinput when running Makima as a systemd service, _but_ I'm pretty confident that it should work now

Let me know if this solves the issue, and again, thanks for the detailed info

**Comment by cyber-sushi** [comment]
> I suggest linking to kdotool repo in docs

Will do

> makima runs as root

Not exactly, if you run it as a systemd service with `User=your_user` and `Group=input` (like you're doing), then Makima runs as your user and not with elevated permissions. However, it doesn't inherit your shell's environment, it inherits your systemd user environment (which you can see by calling `systemctl --user show-environment`) so if you set `PATH` from .bashrc or .zshrc, it won't be available to Makima. In case you need to pass a different `PATH` to Makima, you can either import it directly into systemd (`systemctl --user import-environment PATH`, or whatever other variable), or you can add it into the systemd unit by adding `Environment=PATH=...`)

But anyway, thank you for the feedback! I'll mention this in the docs as well

**Comment by cyber-sushi** [comment]
Oh, interesting, I'll see if I can do something about that
