### ISSUE TITLE
Some mouse remaps no longer work since v0.9.0

### ISSUE THREAD

**Issue by pintassilgo** [cyber-sushi/makima#14]
This is my config file for my mouse:

    [remap]
    BTN_EXTRA-SCROLL_WHEEL_UP = ["KEY_VOLUMEUP"]
    BTN_EXTRA-SCROLL_WHEEL_DOWN = ["KEY_VOLUMEDOWN"]
    BTN_SIDE-SCROLL_WHEEL_UP = ["KEY_LEFTCTRL", "KEY_LEFTSHIFT", "KEY_TAB"]
    BTN_SIDE-SCROLL_WHEEL_DOWN = ["KEY_LEFTCTRL", "KEY_TAB"]

The volume thing has always worked and it's still fine.
But the last two lines to switch tabs using mouse wheel aren't working since v0.9.0.

**Comment by cyber-sushi** [comment]
Thank you for your report!

I just pushed v0.9.2, let me know if it fixes the issue for you

**Comment by cyber-sushi** [comment]
In v0.9.0 i made some optimizations to reduce mutex locking and memory access, plus an optimization specific to wheel events (which is what initially broke the scroll wheel as mentioned in this issue), so that's probably why the events are being flushed faster now
