### ISSUE TITLE
Running makima changes mouse sensitivity

### ISSUE THREAD

**Issue by leonardo-lena** [cyber-sushi/makima#18]
Pretty simple issue. Makima does what I want it to do: rebind mouse4 and mouse5 to CTRL and SHIFT respectively to act as modifierts, but when I run it, my mouse sensitivity goes up and then returns to normal when I stop it. Haven't found anything in the documentation regarding it so I'm asking if there's a fix for this.

**Comment by cyber-sushi** [comment]
Hello!

When Makima is running, it redirect all of the relative events (mouse movements) from your mouse to a virtual device called "Makima Virtual Pointer".  This means that if you set a specific sensitivity for your mouse in your compositor's/DE's settings, it won't apply to Makima's virtual device. Have you tried changing the sensitivity of the virtual device to match the sensitivity of your mouse?

**Comment by leonardo-lena** [comment]
ah that's probably why. No I have not because I didn't know how it worked under the hood. Could you point me to a resource explaining how I would change the sensitivity of said virtual device?

**Comment by cyber-sushi** [comment]
You can change it from your compositor's config file or settings (this isn't really related to Makima)

For example, on Hyprland you can refer to [these docs](https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs)

Example:

```
device {
	name = makima-virtual-pointer
	sensitivity = -0.5
}
```

But again, it entirely depends on the compositor that you're using

**Comment by leonardo-lena** [comment]
Okay, using PopOS which is currently still using gnome and therefore GDM. Running `xinput --set-prop <device-id> 157 0.5 0 0 0 0.5 0 0 0 1` halved the speed on both the x and y axis, which is good enough for me. Thank you for the help!

**Comment by cyber-sushi** [comment]
Glad I could help!
