### ISSUE TITLE
Is it possible to enable both sticks as a cursor?

### ISSUE THREAD

**Issue by M4rtineski** [cyber-sushi/makima#23]
I want to use the left stick for quick and big movements and the right stick for slower and more precise movements. Enabling the right stick as a cursor only works when left stick isn't enabled as a cursor.

Edit: I'm trying to assign the mouse movements to the dpad but I don't think that's possible either? Or at least I haven't found a way to do that after lots of troubleshooting... I think I'd prefer dpad over the second stick because it'd allow me to easily move the cursor without changing x or y axis. Example use of that would be marking text to be copied without jumping between lines during that and having to correct it. I already do that with the macropad I have:

![image](https://github.com/user-attachments/assets/f1bc5922-144d-475d-a72a-c9c99e18c565)

Visual representation of the use case (it's also nice for aligning screenshots):

![image](https://github.com/user-attachments/assets/f0aa7ca5-efa6-437b-8a20-d0d427768392)

**Comment by cyber-sushi** [comment]
Hello!

I think being able to control the mouse cursor using any key (including dpad) would be absolutely useful, I'll add it as soon as possible, thank you for your request

**Comment by M4rtineski** [comment]
Cool! Can you also look into acceleration and max speed of the cursor (assuming it's not tied to the system)?. So stuff like: initial speed, acceleration, max speed. This way you gain much more control/precusion despite being limited to 1/0 state of the button. Small movements by tapping and big movements by holding.

**Comment by M4rtineski** [comment]
I feel like asking in advance, will it be possible to use shortcuts/modifiers with keys that have a mouse movement/scroll assigned? Or even using the shortcuts to activate the movement/scroll. Because I can't do that on the sticks for example. My controller has 2 programmable buttons on the bottom and I'm using them a lot to switch between functions of the buttons on the fly:

![image](https://github.com/user-attachments/assets/9450ea36-bc5e-4264-bb70-410159d08428)

This info would be useful to prepare my layout in advance and get used to it before this comes out. My base layout is fully set up, and I'm already filling out the second "layer" so I'd rather change it as needed before I add even more shortcuts and complicate the job for my future self. Thanks.

---

And a second topic I'm curious about is how you're planning to handle acceleration reset (assuming there will be acceleration at all). Will acceleration be tied to each button separately or will they share acceleration? I don't have strong opinions on that but I noticed that my macropad shares acceleration between buttons. If for example I hold the button to move button to the right and it reaches max speed and I tap a top or down button those taps will have maximum acceleration as well. Even the opposite button press will switch the direction of movement while keeping the acceleration. All that as long any of the movement keys is held at any time, a break in movement will reset the acceleration.

It's just something I thought I'd share. :p

~~(I really hope I don't come out as wanting to pressure you. I love this project and it saved my ass with using my controller for advanced stuff while being simple. :x)~~

**Comment by cyber-sushi** [comment]
>will it be possible to use shortcuts/modifiers with keys that have a mouse movement/scroll assigned

If you mean for example `KEY_LEFTCTRL` + `KEY_UP` => move the cursor up, while just `KEY_UP` does something else, then yes, it already works properly on my local repo, but I haven't implemented acceleration and speed yet so I'll push the commits when everything is ready

>Because I can't do that on the sticks for example

You can activate/deactivate cursor/scroll movements on analog stick through a modifier [like this](https://github.com/cyber-sushi/makima?tab=readme-ov-file#lstick_activation_modifiers-and-rstick_activation_modifiers), but if you mean swapping function entirely (from "scroll" to "cursor" to "bind") then no. Which one would you need in this case?

>Will acceleration be tied to each button separately or will they share acceleration

I think it would be more consistent if acceleration was shared between all buttons, otherwise just changing direction would reset it and it would be annoying imo

>switch between functions of the buttons on the fly

Depending on your preference, it might be worth considering [layout hotswapping](https://github.com/cyber-sushi/makima?tab=readme-ov-file#layout-hotswapping), so you don't need to press a modifier for everything

**Comment by M4rtineski** [comment]
>You can activate/deactivate cursor/scroll movements on analog stick through a modifier [like this](https://github.com/cyber-sushi/makima?tab=readme-ov-file#lstick_activation_modifiers-and-rstick_activation_modifiers), but if you mean swapping function entirely (from "scroll" to "cursor" to "bind") then no. Which one would you need in this case?

Personally I've tried using a modifier on a stick to change the cursor movement speed which is why I figured I'd ask the question in advance to confirm things.

>Depending on your preference, it might be worth considering [layout hotswapping](https://github.com/cyber-sushi/makima?tab=readme-ov-file#layout-hotswapping), so you don't need to press a modifier for everything

Yes, I'm well aware of that and decided to go with what I'm doing currently. I'm still figuring things out so I may switch to actual layers later depending on how it goes. One of the reasons I didn't try out layers yet is because I'm not confident in remembering which layer I'm on currently. With modifiers I can tell easily because I physically hold the button to be on it and it always defaults to the main behavior. And the other reason is that the main behavior are things I use the most commonly while the things I use shortcuts for are an enhancement of sorts (besides the things that just didn't fit on base layout). I use the controller to control my pc and mainly a web browser so I'm not really in position where one layout for specific situation/app would be enough either and I'd need to constantly switch between them while having to keep track of which one I'm on and not mess things up with wrong action. 

(I just woke up, I hope my sentences are clear. xd)

**Comment by cyber-sushi** [comment]
Version 0.10.0 is out with the new features, let me know if everything works fine for you

**Comment by M4rtineski** [comment]
That was quick! Will try it in a bit and let you know. Merry xmas! 🎉

**Comment by M4rtineski** [comment]
Ok, not sure if I'm supposed to close this issue and start a new one but for now I will put the feedback here:

---

1.) Quick taps on scroll button don't do anything if I want to for example jump by a specific amount of scrolls or even only one. To do that I need to hold it for a moment and release each time I want a smaller jump which isn't responsive or hold it and be stuck at the pace of acceleration when I still want a quick but slightly bigger movement like 3 jumps for example. Continuing the example of 3 jumps there's also the issue of precision where I may release too soon or too late by accident requiring correction which would have been otherwise easier and quicker with 3 taps. Correction would also be quicker when releasing at wrong moment if I could just quickly tap to correct it. 

As soon the button is pressed it would be good for there to be one initial scroll movement before the loop starts.

---

2.) Cursor movement has a similar problem where small quick taps almost don't move the cursor at all (It moves too little for the small movements I need). I need to hold it for a bit until it starts to move at a reasonable pace which again doesn't feel responsive and doesn't allow me for quick/small corrections in position. So far I've found myself comfortable with 0.2 acceleration (seems similar to my macropad) but when testing the taps on 0.5 (the speed I have set is 10 and it's also similar to my macropad) I found them more responsive and more or less close to my macropad mouse movement taps. But this acceleration is big so even those small taps differ lots in movement even with very minimal differences in tap (or micro hold if you will) time and outside the taps it's practically only maximum speed which I don't want to be limited to. 

<details>
<summary>When testing my macropad taps they look like this:</summary>

![image](https://github.com/user-attachments/assets/559bf6af-4652-4b95-b32c-371d116236fd)
</details>

<details>
<summary>Holding looks like this:</summary>

![image](https://github.com/user-attachments/assets/95ff9f93-6caf-4571-885b-2bcc165caecd)
</details>

<details>
<summary>Meanwhile makima taps look like this:</summary>

![image](https://github.com/user-attachments/assets/51a0a275-fd78-49c9-8bcb-c83d34ffda09)
</details>

Sometimes quick taps won't register I assume for the same reason as scrolling. I tested it with command activation to ensure that it isn't a controller thing or overall makima thing and confirmed it to be not. Command activated each time no matter how short the tap so it's cursor movement specifically. Doesn't matter currently but it's potentially useful context for my proposed solution. :p

<details>
<summary>And holding looks like this:</summary>

![image](https://github.com/user-attachments/assets/50cd8eb6-0662-4dd3-a4a4-fc4c1d09b913)
</details>

If my assumption is right then perhaps adding a setting for the customisable cursor "jump" on the initial press would make it work the way I want? I'd test it myself with ydotool activated on press alongside makima but I don't know how to do that. And if I knew I'd probably just use that as a solution. lol

Or maybe initial speed that you can set. For example setting it to 5-10% from the start would probably give a smoother result than jumping by x pixels, abruptly stopping, and slowly picking up speed.

---

3.) Makima lists A LOT of devices. Each time I stop and restart the script a new ones are added/created. Don't know if it was like this before but I'm going to guess that it was. I restart makima lots because I iterate on the layout lots so I have a bit at the moment of taking the screenshot. If it's something that's not supposed to happen then I can make an issue for that specifically later.

<details>
<summary>Image:</summary>

![image](https://github.com/user-attachments/assets/e12e2e26-9210-4b42-b8cc-789867b1a840)
</details>

There isn't actually this many devices, there's just a big gap in numbering.

---

4.) Broken speed when moving the cursor diagonally. (Using a stick as well.)

When I move the cursor diagonally it seems to speed up considerably. When I hold the button in one direction it takes ~6 seconds to reach from one side of the screen to the other. When I hold two buttons to move it diagonally it reaches the other side in ~4 seconds. The times were calculated in head with a clock on the screen over an hour ago and I kept them in head only so don't take them at face value.

This was also the case with the stick in previous versions but I assumed that it was just how my controller passes the input data to makima. It makes the stick weird to use because the speed is inconsistent between diagonal and singular axis movements. Makes it a bit harder to be accurate as well because it slows down and speeds up which is hard to be accurate with.

---

Since I initially started writing the feedback the message grew much longer than I expected and I made a looooot of edits as I went. I hope nothing was lost during the edits and everything's clear.

Regardless of the issues I have it's still infinitely better to have the functionality this way than not at all. Thank you for creating and maintaining makima. <3

**Comment by cyber-sushi** [comment]
First of all, thank you so much for all the feedback!

I'll try to reply to everything:

1) Currently Makima sends high res scroll events (relative events number 11 and 12) in order to scroll smoothly, _but_ as you mentioned, this means that there's a delay between the key press and the actual scroll because libinput (I think) waits for a certain amount of "movement" before registering the scroll, I assume that's to avoid accidental scroll on devices such as touchpads. The solution would be to send a single regular scroll event (relative events number 6 and 8) whenever a key is pressed and then continue with the high res events, but I'll have to do some tests to see how it feels

2) I think this is a different issue and it's most likely due to float approximation. Actually, issue 1 could be a combination of what I mentioned _and_ an issue with float approximation. Anway, I could simply play around with the formula a little bit until things feel better, and setting a minimum initial value like you said (instead of letting it approximate to 0) would probably feel much better, so yeah, that's a pretty good idea

3) Mmhhhhhhhhhhhh that's really weird, it never happened on my machine, it should be just one device for each type. In fact, when Makima is killed, the virtual devices it created should be destroyed. I'll look into it, and opening a separate issue would probably make sense

4) Yeah, Pythagoras's fault I guess ahah. When both axes are activated, the resulting vector is equal to the hypotenuse of the two axes, so the speed is ~1.414 times the normal speed. I should write a formula to normalize that

Anyway, thanks so much again, I'll start working on it in the next few days!

**Comment by M4rtineski** [comment]
1.) In firefox I don't experience smooth scrolling which is why I was using the term "jump". On steam I noticed today that it's smooth like you say it's supposed to be. Dunno how much it would complicate things but perhaps an optional setting would make the most sense given that people use different things?

And like you suggest there seems to be a delay on initial press. When you quickly release and press the key again to continue the scroll it has this nice slow ramp up in speed when testing on steam. Otherwise when you start scrolling it shoots off slightly due to activating a little later with the acceleration built up. 

2.) I think I may try recording a short clip to visualise the cursor movement from makima vs my macropad which I find just right. It has this nice smooth kickoff which was also visualised in my screenshots. I assume it's hard to understand what I mean without a comparison.

My macropad supposedly uses something like this: https://en.wikipedia.org/wiki/Mouse_keys

I doubt it's useful but figured I'd share it anyway. I found that out here: https://github.com/search?q=org%3Athe-via+acceleration&type=code

And more specifically here: https://github.com/the-via/qmk_firmware/blob/8f0bf52b250406d0063726d4c62c78e84c1d1f2b/docs/feature_mouse_keys.md?plain=1#L79

3.) Alright, will do that later.

4.) To clarify (coz I'm not sure what your words mean uwu), when I move the cursor at 'y' axis it moves at 'a' speed on this axis but when I move it at 'y' and 'x' axes it moves at 'b' speed on this 'y' axis. It makes sense for the diagonal movement specifically to be faster due to overlaping of 'y' and 'x' axes but it also affects the movement speed of each axis for some reason.

[Time skip]

I'd test if I'm actually tripping or not when it comes to button specifically  but I've been fighting my sleepiness for a while and I can't keep my consciousness up anymore to do the tests. I've started writing this message ~3 hours ago but wasn't able to finish it with tests and examples like I did previously. I'm not proofchecking anything, hopefully it holds together, night. :p

**Comment by M4rtineski** [comment]
4.) Alright, somehow it didn't cross my mind to disable acceleration in the settings for the makima pointer device. Especially when ydotool pointed that out to me already that it can mess with the movements. It resolved this weird behavior and the stick isn't so unpleasant to use anymore.

The button movements also don't seem to have this jump in speed on singular axis when both axes are activated.

Now that I have this weird behavior out of my way I can confirm that some correction on speed when moving horizontally with buttons would be a nice to have but for me personally it's not a roadblock that ruins the experience.

<details>
<summary>And this is purely as an example but my macrodeck does smth like this and is comfortable:</summary>

![image](https://github.com/user-attachments/assets/92bbab69-9fc5-4731-ae84-af51a50d0dc4)
</details>

---

Closing this issue as not planned because it was technically created for a different topic than what we were discussing and I don't have an urgent need for it anymore.

**Comment by cyber-sushi** [comment]
That's a lot of useful feedback, thank you a lot!

I should probably add a notice in the docs about disabling acceleration for the pointer device, and other than that, I'll use your macropad's output as an example for how the "feeling" should be

And thank you for such throughout testing, I wish all issue reports were like this ahah
