### ISSUE TITLE
Sleep/pause argument between commands. (Request)

### ISSUE THREAD

**Issue by M4rtineski** [cyber-sushi/makima#28]
Soooooooo (lore dump time) I'm trying to figure out how to move my cursor to a specified location with a button press on my controller. I found this thing called 'ydotool' which supports that BUT there's like 50/50 (or random) chance of it working properly. When using one command with absolute position argument I was experiencing what I described above so I figured I will just use relative position to move the cursor to the top left corner and move the cursor where I want from there. This is also how this absolute argument works in the backend. So what I made in makima is:

`BTN_THUMBR-BTN_DPAD_UP = ["ydotool mousemove -x -3000 -y -3000", "ydotool mousemove -x 1360 -y 425"]`

But that didn't work so I decided to break it down further because when I had higher negative values for the initial reset command I noticed it being more junky than with lower values. I thought it will put less pressure on pc or smth:

`BTN_THUMBR-BTN_DPAD_UP = ["ydotool mousemove -x -3000 -y -1", "ydotool mousemove -x -1 -y -3000", "ydotool mousemove -x 1360 -y 425"]`

But that didn't work either and because the action was broken up into 3 separate pieces I noticed that they randomly work while the other ones don't and sometimes the whole thing works. So to test things out I assigned each of those 3 commands to a separate button:

`BTN_THUMBR-BTN_DPAD_UP = ["ydotool mousemove -x 1360 -y 425"]`

`BTN_THUMBR-BTN_DPAD_RIGHT = ["ydotool mousemove -x -3000 -y -1"]`

`BTN_THUMBR-BTN_DPAD_LEFT = ["ydotool mousemove -x -1 -y -3000"]`

And when testing them out and manually initiating each action to achieve the result the thing worked each time no problem. This means that there are some problems when everything is tried to be done ASAP but otherwise it's alright. This isn't a makima issue, I may have failed to address that earlier. This whole process leaded me to make this request because it should (damn hopefully) solve this issue I have.

Edit: There's also a possibility of the commands activating in a random order and me misinterpreting what I saw happening to cursor. But my request would stay relevant in that situation as well.

**Comment by cyber-sushi** [comment]
Hello!

I think the sleep feature should be the shell's job, have you tried something like:

`BTN_THUMBR-BTN_DPAD_UP = ["ydotool mousemove -x -3000 -y -1 && sleep 0.1 && ydotool mousemove -x -1 -y -3000 && sleep 0.1 && ydotool mousemove -x 1360 -y 425"]`?

If all you need is a delay, that should do the trick

**Comment by M4rtineski** [comment]
Thank you! Works every time. Didn't cross my mind that shell could have this already.
