### ISSUE TITLE
RS Up, Down, Left, & Right can't be remapped.

### ISSUE THREAD

**Issue by LovelyLince** [cyber-sushi/makima#29]
When I hold LT & move RS leftward, I want KEY_5 to be sent. Here's my code (look under `# ---------- Sub Palette ----------`):
```
[remap]
# ---------- Main Layer ----------
# Menu
BTN_MODE = ["KEY_ESC"] # Xbox Button = ESC
BTN_SELECT = ["BTN_THUMBL"] # Select = LS Click
# LS
BTN_THUMBL = ["BTN_SELECT"] # LS Click = Select
# ---------- Sub Palette ----------
# Menu
BTN_TL2-BTN_START = ["KEY_9"] # LT + Start = 9
# D-Pad
BTN_TL2-BTN_DPAD_LEFT = ["KEY_1"] # LT + D-Pad Left = 1
BTN_TL2-BTN_DPAD_UP = ["KEY_2"]
BTN_TL2-BTN_DPAD_RIGHT = ["KEY_3"]
BTN_TL2-BTN_DPAD_DOWN = ["KEY_4"]
# RS
BTN_TL2-RSTICK_LEFT = ["KEY_5"] # LT + RS Left = 5
BTN_TL2-RSTICK_UP = ["KEY_6"]
BTN_TL2-RSTICK_RIGHT = ["KEY_7"]
BTN_TL2-RSTICK_DOWN = ["KEY_8"]
# ---------- Swap Weapons ----------
# Face
BTN_THUMBL-BTN_NORTH = ["KEY_KP1"] # Select + X = Numpad 1
BTN_THUMBL-BTN_WEST = ["KEY_KP2"] # Y
BTN_THUMBL-BTN_EAST = ["KEY_KP3"] # B
# RS
BTN_THUMBL-RSTICK_LEFT = ["KEY_KP7"] # Select + RS Left = Numpad 7
BTN_THUMBL-RSTICK_UP = ["KEY_KP8"]
BTN_THUMBL-RSTICK_RIGHT = ["KEY_KP9"]

[settings]
GRAB_DEVICE = "true" # Allow Makima exclusive control of this device.
```

Pressing LT + RS Left does nothing, but for example, LT + D-Pad Left does send KEY_1. I tried omitting `BTN_TL2-` & just writing `RSTICK_LEFT = ["KEY_5"]`. However, this doesn't work either. I checked input-event-codes.h, but `RSTICK_LEFT` wasn't listed. Also, evtest just shows RS as `ABS_RX` & `ABS_RY`. These values can't be remapped either.

**Comment by cyber-sushi** [comment]
Hello,

have you tried putting `RSTICK = "bind"` under `[settings]`?

Both analog sticks can be used to move the cursor, scroll or be binded to some event, but if you don't specify anything, they default to `"disabled"`

You can find a reference in the docs [here](https://github.com/cyber-sushi/makima/tree/main?tab=readme-ov-file#lstick-and-rstick)

**Comment by LovelyLince** [comment]
After adding `RSTICK = "bind"`, I can now remap RS. Sorry about that, but I'm having a different issue now. Should I open a separate issue?
