### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by ninfranko** [cyber-sushi/makima#6]

**Comment by cyber-sushi** [comment]
Hello, can you explain more in detail?
What output do you get if you execute Makima from a terminal?

**Comment by cyber-sushi** [comment]
You need to rename the .toml config file according to your device's name, which you can retrieve using `evtest`. If Makima detects an input device with a name that _exactly_ matches your config file's name, it'll start reading the input events

Refer to the [documentation](https://github.com/cyber-sushi/makima?tab=readme-ov-file#configuration) for more info

Also, when you launch Makima, there's no need to use `./makima evtest`, just `./makima` is enough

Let me know if it works

**Comment by cyber-sushi** [comment]
I've released version 0.4.3, which adds deadzone configuration through the DEADZONE parameter (and I've also fixed the Xbox config file to include the GRAB_DEVICE parameter), so just download the new version (and config file) and it should work

ABS_X and ABS_Y can only be used for cursor movement and 2D scroll at the moment. All ABS events have their own quirks so they need to be coded in manually, [here in the docs](https://github.com/cyber-sushi/makima/tree/main#bindingsaxis-and-combinationsaxis) you can find a list of the ABS events that can be remapped to keys currently, but if you need it, I can also add remapping for the analog sticks

**Comment by cyber-sushi** [comment]
I have added analog stick rebinding for each direction in version 0.5.0, plus deadzone configuration per stick, so that should be it for this issue

Also take a look at the new config files since I have reworked the syntax to be simpler
