### ISSUE TITLE
UTF-8 error when using vim

### ISSUE THREAD

**Issue by nougatbyte** [cyber-sushi/makima#7]
Hi,

When editing the configuration files with vim and trying them out I ran into an Error: "stream did not contain valid UTF-8".
This is because I was using vim in one terminal and restarting makima in the other terminal.

When only saving but not closing vim it creates files like ".8BitDo Pro 2.toml.swp" and makima tries to interpret them as config files.
As vim is pretty widespread it would be nice if files starting with a dot or ending with .swp could be omitted when reading configurations.

Thanks for the great software btw!

**Comment by cyber-sushi** [comment]
Done! I've pushed version 0.4.4, now Makima should ignore all files that start with `.` and files that don't end with `.toml`

Let me know if everything works properly, and thank you for the detailed report
