### ISSUE TITLE
Modifier commands only work in specific order

### ISSUE THREAD

**Issue by dannyglover** [cyber-sushi/makima#9]
It seems with certain modifiers, they only work in a specific order. I'd like for this command to be executed (xbox controller) by holding Select+LT then pressing A, but it only works if I hold Select+A then press LT. Any idea why?

This doesn't work
`BTN_SELECT-BTN_TL2-BTN_SOUTH = ["plasma-systemmonitor"]`
However, this does 
`BTN_SELECT-BTN_SOUTH-BTN_TL2 = ["plasma-systemmonitor"]`

Interestingly, this fails to execute the command no matter which comes first (LT or RT)
`BTN_SELECT-BTN_TR2-BTN_TL2 = ["plasma-systemmonitor"]`

EDIT: adding the Select, LT or A (or a combination of all of them, minus A or including A) doesn't seem to help the situation.

Thank you.

**Comment by cyber-sushi** [comment]
Hello, thank you for your report!

This is most likely because triggers are an ABS event and not a KEY event, so Makima isn't able to interpret them as modifiers and they only work when used last. I'll look into it tomorrow, it _should_ be an easy fix

**Comment by dannyglover** [comment]
> Hello, thank you for your report!
> 
> This is most likely because triggers are an ABS event and not a KEY event, so Makima isn't able to interpret them as modifiers and they only work when used last. I'll look into it tomorrow, it _should_ be an easy fix

That would be great, thank you very much!
PS: I'm the zion guy from reddit.

**Comment by cyber-sushi** [comment]
It was an entirely different issue, just a simple bug regarding gamepad triggers

I pushed a fix, let me know if everything works now!

**Comment by dannyglover** [comment]
> It was an entirely different issue, just a simple bug regarding gamepad triggers
> 
> I pushed a fix, let me know if everything works now!

Hey. I looked at the commit history and I don't see the fix pushed?

Thanks :)

**Comment by cyber-sushi** [comment]
Commit [a535543](https://github.com/cyber-sushi/makima/commit/a5355432b42407af6344afa9dd9ca6095f63ecc8)

**Comment by dannyglover** [comment]
> Commit [a535543](https://github.com/cyber-sushi/makima/commit/a5355432b42407af6344afa9dd9ca6095f63ecc8)

Right, so I've never used git tags before, (embarrassing as a developer, I know... my software rarely gets released :/), hence why I didn't see the commit. Anyway... so I did the following just to get the latest changes (including the commit you mentioned). 

- `git checkout tags/v0.7.2`
- `cargo build --release`
- `chmod +x targets/release/makima`
- `sudo mv target/release/makima /usr/bin`

I then ran makima `sudo -E makima` and attempted this command: 
``
`[commands]
BTN_SELECT-BTN_TL2-BTN_SOUTH = ["plasma-systemmonitor"]
```
Still no dice, unfortunately. The good news, is that I tried your changes for #10 and that works great.

**Comment by cyber-sushi** [comment]
Don't worry, I don't know how to use git as well ahah

Yes, I've tried with
```
[commands]
BTN_SELECT-BTN_TL2-BTN_SOUTH = ["nautilus"]
```

and 
```
[commands]
BTN_SELECT-BTN_TL2-BTN_TR2 = ["nautilus"]
```
on my PS4 controller and they work fine

But maybe I have a clue: do you have BTN_TL2 bound to something else, singularly? Like `BTN_TL2 = ["KEY_A"]` or something similar?
Because that means that for the purpose of being a modifier, `BTN_TL2` now counts as `KEY_A`, so it won't fire your command (but it will fire if you bind `BTN_SELECT-KEY_A-BTN_SOUTH = ["plasma-systemmonitor"]`, for example)

**Comment by dannyglover** [comment]
> Don't worry, I don't know how to use git as well ahah
> 
> Yes, I've tried with
> 
> ```
> [commands]
> BTN_SELECT-BTN_TL2-BTN_SOUTH = ["nautilus"]
> ```
> 
> and
> 
> ```
> [commands]
> BTN_SELECT-BTN_TL2-BTN_TR2 = ["nautilus"]
> ```
> 
> on my PS4 controller and they work fine
> 
> But maybe I have a clue: do you have BTN_TL2 bound to something else, singularly? Like `BTN_TL2 = ["KEY_A"]` or something similar? Because that means that for the purpose of being a modifier, `BTN_TL2` now counts as `KEY_A`, so it won't fire your command (but it will fire if you bind `BTN_SELECT-KEY_A-BTN_SOUTH = ["plasma-systemmonitor"]`, for example)

Here's my complete config:
```
# for some reason, the button mappings are incorrect?, these are the correct mappings for the face buttons
# east = B
# south = A
# north = X
# west = Y

[remap]
# SELECT + B: The Classic Alt+F4
BTN_SELECT-BTN_EAST = ["KEY_LEFTALT", "KEY_F4"]
# SELECT + Y: Quits All Wine Processes + Steam, Lutris & Heroic (key command linked to script in keyboard shortcut settings page)
BTN_SELECT-BTN_WEST = ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_LEFTSHIFT", "KEY_K"]
# SELECT + GUIDE BUTTON: Launch EmulationStation-DE (key command linked to script in keyboard shortcut settings page)
BTN_SELECT-BTN_MODE = ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_LEFTSHIFT", "KEY_E"]
# SELECT + DPAD DOWN: Put Computer To Sleep
BTN_SELECT-BTN_DPAD_DOWN = ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_LEFTSHIFT", "KEY_PAGEDOWN"]
# SELECT + LT: Mouse Right Click
BTN_SELECT-BTN_TR = ["BTN_RIGHT"]
# SELECT + LT: Mouse Left Click
BTN_SELECT-BTN_TL = ["BTN_LEFT"]

[commands]
BTN_SELECT-BTN_TL2-BTN_SOUTH = ["plasma-systemmonitor"]
#BTN_SELECT-BTN_SOUTH-BTN_TL2 = ["plasma-systemmonitor"]

[settings]
LSTICK_SENSITIVITY = "6" #sensitivity when scrolling or moving cursor, lower value is higher sensitivity, minimum 1
RSTICK_SENSITIVITY = "15" #sensitivity when scrolling or moving cursor, lower value is higher sensitivity, minimum 1
LSTICK = "disabled" #cursor, scroll, bind or disabled
RSTICK = "cursor" #cursor, scroll, bind or disabled
LSTICK_DEADZONE = "5" #integer between 0 and 128, bigger number is wider deadzone, default 5
RSTICK_DEADZONE = "64" #integer between 0 and 128, bigger number is wider deadzone, default 5
16_BIT_AXIS = "true" #necessary for Xbox controllers and Switch joycons, use false for other controllers
GRAB_DEVICE = "false" #gain exclusivity on the device
RSTICK_ACTIVATION_MODIFIERS = "BTN_SELECT"
```

PS: That selinux stuff I mentioned before to you, you also need to run this again, whenever you update the binary in `/usr/bin` (found that out today):

`sudo restorecon -v /usr/bin/makima`

**Comment by cyber-sushi** [comment]
I tried copying your config over and it works for me

I'll see if I can ask a friend to lend me their Xbox controller just in case, what model are you using specifically?

**Comment by dannyglover** [comment]
> I tried copying your config over and it works for me
> 
> I'll see if I can ask a friend to lend me their Xbox controller just in case, what model are you using specifically?

Maybe I didn't grab the commit properly then. I'll try again.

I'm using an Xbox Elite v2. 
Thanks again.

**Comment by cyber-sushi** [comment]
Found the issue! Xbox One controllers, unlike other controllers, don't emit a `BTN_TL2`/`BTN_TR2` event when the trigger is pulled, they only emit absolute axis events, that's why it was working on my controller but not on yours

I'm gonna fix it with the next release, along with some other changes

**Comment by dannyglover** [comment]
> Found the issue! Xbox One controllers, unlike other controllers, don't emit a `BTN_TL2`/`BTN_TR2` event when the trigger is pulled, they only emit absolute axis events, that's why it was working on my controller but not on yours
> 
> I'm gonna fix it with the next release, along with some other changes

Aha! Nice sleuthing 👍

That makes perfect sense. Looking forward to that next release, when you get time to do it. I'll test it at my end as soon as it's out. 

Sorry for not getting back to you (re: my last comment).. I ended up falling asleep at the keyboard last night. 

Thanks for being so responsive to these reports. It's extremely refreshing.

**Comment by cyber-sushi** [comment]
It should work properly in version 0.8.1!

I've only been able to test it with my controller _but_ all other axis events (DPAD and sticks) work fine now when used as modifiers, which means triggers should work too

**Comment by dannyglover** [comment]
> It should work properly in version 0.8.1!
> 
> I've only been able to test it with my controller _but_ all other axis events (DPAD and sticks) work fine now when used as modifiers, which means triggers should work too

Sorry for the late reply. I haven't been well.
Just tried out the new version and it works perfect. Great job!
